# Generated by Django 6.1.1 on 2026-09-15 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Boya')),
                ('ubicacion', models.CharField(max_length=255, verbose_name='Ubicación o Coordenadas')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boyas', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('temperatura', 'Temperatura'), ('ph', 'pH'), ('turbidez', 'Turbidez'), ('oxigeno', 'Oxígeno Disuelto')], max_length=50, verbose_name='Tipo de Sensor')),
                ('valor_actual', models.FloatField(default=0.0, verbose_name='Último Valor Medido')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Medición')),
                ('boya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='boyas.boya', verbose_name='Boya')),
            ],
        ),
    ]
