# Generated by Django 6.1.1 on 2026-09-16 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boyas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='valor_actual',
        ),
    ]
