# Generated by Django 6.1.1 on 2026-09-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boyas', '0002_remove_sensor_valor_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='valor',
            field=models.CharField(default='---', max_length=50, verbose_name='Valor Actual'),
        ),
    ]
