# Generated by Django 6.1.1 on 2026-09-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boyas', '0003_sensor_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='rango_max',
            field=models.FloatField(default=100.0, verbose_name='Rango Máximo'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='rango_min',
            field=models.FloatField(default=0.0, verbose_name='Rango Mínimo'),
        ),
    ]
